### ISSUE TITLE
Localized system properties

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#109]
There is an issue with the System.Title and other "named" properties.
If you have a localized Solid Edge, those properties will be translated into the user language.
The actual method looks for the exact name and it will return a property not found error.

A possible solution would be to create a map SystemPropertyName --> PropertyIndex and use the index to get the correct property. This issue is present only when editing properties through Solid Edge; the structured storage method is not affected.

**Comment by rmcanany** [comment]
Sounds like a good idea to me.  That must be a recent change.  I had a user early on who discovered he had to use English for those properties, even though they were presented in Polish in SE.

**Comment by rmcanany** [comment]
I recently saw a list of system properties that SE actually supports.  Was that from you?  

Also, the property indices you mention, would those be the item number in whatever stream holds the property, or something else?

**Comment by farfilli** [comment]
I have created the list in combo box for system properties, but not created a mapped index to use in the PropertySet
Structured storage is always in English so the problem occurs only when edit on Solid Edge

**Comment by farfilli** [comment]
fixed with #118 
I haven't created a specific function that returns the property but wrote it directly inside the GetProp sub.
It may be useful for other usage to create a proper function.

**Comment by rmcanany** [comment]
Did a quick test and all seems to be working.  I'll do some more before I close this out.

I added `Material` and `Sheet Metal Gage` to the checks in GetProp.  

In TaskEditProperties, at one point I have:
`If (PropertyName.ToLower = "material") And (PropertySetName.ToLower = "system")`
Correct me if I'm wrong, but since the ComboBox entries are in English, this should still work even if a user is running in Localized mode, right?

**Comment by farfilli** [comment]
Yes, It works and you don't need the toLower statement at the combo box entries are not editable.

The problem is on the property name that SolidEdge APIs returns localized and therefore you need the mapping.

Material it's a strange beast anyway. Even if through API is present in the PropertySet it's not in the UI and not in the Structured Storage. Said that I don't know if it come localized or not, I have to check it but can't till next Tuesday.

**Comment by farfilli** [comment]
It's gonna be a huge release the next one 😀🔝

**Comment by rmcanany** [comment]
@farfilli When you get to it, let me know what you find about the language for Material, etc.  If they're localized, I have a few things to fix.

**Comment by farfilli** [comment]
@rmcanany the property Material is not localized and it is in MechanicalModelling.Item(1)

**Comment by rmcanany** [comment]
OK.  Thank you.  

Same with the rest of them, too?  (Density, Coefficient of Thermal Expansion, etc.)

**Comment by farfilli** [comment]
That's a mix of translated and English.
I will send you a screenshot tomorrow, not in front of PC now.

I was thinking that for standard properties we could map them all, there will be no need to find them in this way.

**Comment by rmcanany** [comment]
Yeah, mapping them sounds like better way to go.  I'll look into it.

**Comment by farfilli** [comment]
I have highlighted the localized properties; by the way density is not part of the properties but its an exposed variable
![image](https://github.com/user-attachments/assets/3b10cccd-d71a-418c-9b52-b79bf7b2bb1f)
![image](https://github.com/user-attachments/assets/9472474b-26c8-4de5-afad-950aea919f18)

**Comment by rmcanany** [comment]
Very helpful.  Thank you!

**Comment by rmcanany** [comment]
@farfilli @ChrisClems @lrmoreno007 

Hey All, I'm going to take a look at this today.  Once this one is fixed, I think we're ready to do a release.  I have been working on the [release notes](https://github.com/rmcanany/SolidEdgeHousekeeper/blob/master/release_notes.md).  When you get a chance, please look over your sections and let me know if I got anything wrong or left anything out.  Thank you!

**Comment by farfilli** [comment]
@rmcanany the link on DirectEdit leads to the wrong position. 

Thoughts:
To be able to implement the expression editor I have used those 2 components:
- [CoreCLR-NCalc](https://github.com/sklose/NCalc2)
- [FCTB](https://www.codeproject.com/Articles/161871/Fast-Colored-TextBox-for-syntax-highlighting-2)(FastColoredTextBox)

To be able to implement the Direct edit of properties I have used this component:
- [OpenMcdf](https://github.com/ironfede/openmcdf)

I would check on license terms if you need to mention them on the ReadMe; I would mention them anyway they are all great components

**Comment by rmcanany** [comment]
Good points, especially about the external components.  I'll get that fixed.

**Comment by rmcanany** [comment]
Superseded with https://github.com/rmcanany/SolidEdgeHousekeeper/issues/123.  Closing.
