### ISSUE TITLE
CropImage():  Move to CommonTasks.vb and remove dependency on ffmpeg

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#12]

**Comment by farfilli** [comment]
Done

I would spend a word on how this is done, maybe it is just not clear to me the final scope of the function but at least, wouldn't a view fit be done before generate the images?

**Comment by rmcanany** [comment]
I imagine almost everyone would want to fit the view before it gets saved as an image.  However, since that command is available already, I thought it would add a tiny bit of flexibility to give someone the option not to.  For example, if they wanted to create a separate external program that zooms the window out 10% or something like that.

Anyway, closing for now.  Thank you!
