### ISSUE TITLE
ClickOnce Installation

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#14]
It would be good to create a ClickOnce installation that checks the online repository for updates.
In this way for a user would be much easier to install Housekeeper and get automatic updates.

With local resources, it works great and it is the way I distribute software in my network, I have never done it with an online repository but it's sure possible, SeSpy works this way.

**Comment by rmcanany** [comment]
Very cool!  I'll read up on it.

**Comment by farfilli** [comment]
I followed this tutorial to do it; it seems to work even if sometimes the update at open doesn't trigger, haven't figured out it yet

https://stackoverflow.com/questions/13512029/is-it-possible-to-offer-a-clickonce-installer-on-github

**Comment by rmcanany** [comment]
On hold for now.

**Comment by rmcanany** [comment]
Closing for now.
