### ISSUE TITLE
Brighter main icon

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#142]
@rmcanany all the icons used in the software are in color-flat style; this is a style that I like and have used in the whole UI.
The main icon is in a different style, and I suggest brightening it a bit to match the other icons better.

My suggestion in the attachment 
![image](https://github.com/user-attachments/assets/49304546-f565-4dfa-8dec-8010c485d17d)

[Housekeeper_Bright.zip](https://github.com/user-attachments/files/17259602/Housekeeper_Bright.zip)

**Comment by rmcanany** [comment]
Sure, go for it.

**Comment by farfilli** [comment]
Implemented with #143

**Comment by rmcanany** [comment]
Closing as complete.  Thank you!
