### ISSUE TITLE
Change Document Status handling from DM to Structured Storage

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#149]
Two properties are involved in a Document Status change:
- Status in `ExtendedSummaryInformation`
- Security in `SummaryInformation`

`UtilsCommon` has an `Enum` with the mapping from Status to Security

```
    Public Enum StatusSecurityMapping
        ssmAvailable = 0
        ssmInWork = 0
        ssmInReview = 0
        ssmReleased = 4
        ssmBaselined = 4
        ssmObsolete = 4
    End Enum
```

**Comment by farfilli** [comment]
I have added Status and Security to the Direct Stream function

**Comment by rmcanany** [comment]
Good deal.  I'll take it from there.  Thank you!

**Comment by rmcanany** [comment]
I've got one for you.  I can get the Status multiple times with no problem.  Once I change the value, every call to OLEGetProp returns Nothing for Status.

**Comment by rmcanany** [comment]
The Type for both Status and Doc_Security is `VTPropertyType.VT_I4`, at least according to `Select Case OLEProp.VTType`.  Reading their class definition for `OLEPropertiesContainer`, I gather that is a 4 byte int.  

I can change Doc_Security any number of times with no problem.

**Comment by rmcanany** [comment]
More info...

I set the Status of this file to Baselined in SE.  File properties dialog looks like this.
![image](https://github.com/user-attachments/assets/f2656f94-8209-445d-ae78-0878931bab3a)

I changed it to Available in SSView.  Now it looks like this in SE file properties.
![image](https://github.com/user-attachments/assets/1855b881-afbe-40dc-951c-302565386ec5)

Note Status doesn't have a Type.  What's weird is, trying both settings, SE still knows the actual one.

Another thing.  When I changed Status and Security in SSView, the type listed on the UI changed from `4 byte signed int` to `signed 64-bit int`.

One more thing.  For some reason if Status = Nothing, SE interprets that as Available.  I've seen that one before.

Anyway, I'm thinking about shelving this one for now.  It would be nice, but not absolutely necessary.  Thoughts?

**Comment by rmcanany** [comment]
Looking through the Issues of OpenMcdf, I see you opened one, https://github.com/ironfede/openmcdf/issues/134, that appears to be related.  

That was closed Sep 16.  My *.dll is from Sep 9.  Maybe I just need the latest file.  Could you please remind me again the best way to get that?

**Comment by farfilli** [comment]
Using the Structured Storage Viewer the names are correctly reported, by now I inserted a patch that in case of Status retrieve the property by its number ("0x00000007") look at here https://github.com/rmcanany/SolidEdgeHousekeeper/commit/1c345e656e7ac10f8f026017a37f205e7b0df4dc#diff-88a141292b82313ad633df1a544fd12f0e8e43eb4a80b7892971fbac041e574dR890

**Comment by farfilli** [comment]
OK, it's fixed now, I did update the DLLs but the references where in another folder, corrected and now works as expected.
Soon the v2.4 of openMCDF will be released so we will not have to worry about DLLs anymore

**Comment by farfilli** [comment]
What about a task that only changes the file status?

**Comment by rmcanany** [comment]
Thanks for that.  I'll check it out.

**Comment by rmcanany** [comment]
All those redundant status gets and sets were for troubleshooting.  I'll clean that up today.

**Comment by rmcanany** [comment]
Works great!  Closing as complete.  Thank you!
