### ISSUE TITLE
Consolidate OLEProp Fetching

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#151]
Add a method, `GetOLEProp`, and call it from `GetOLEPropValue`, `UpdateSingleProperty`, and `TaskEditProperties`.

Also, add missing properties to `SIList`, `DSIList`, and `FunnyList`

**Comment by farfilli** [comment]
Please have a look at my comments here https://github.com/rmcanany/SolidEdgeHousekeeper/pull/153#issuecomment-2416673514

**Comment by rmcanany** [comment]
Added a new issue about transitioning Dictionaries to separate Classes.  The OLEProp fetching is consolidated into one method.  Closing as complete.

**Comment by farfilli** [comment]
I have commented the unused code, you can delete it, thanks

**Comment by rmcanany** [comment]
Will do.
