### ISSUE TITLE
Alert user if only selected files will be processed

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#159]
@farfilli 

[Suggestion](https://community.sw.siemens.com/s/question/0D5Vb00000Lej9IKAR/solid-edge-housekeeper-v20243-is-released) from @64Pacific.

One idea he had was to change the button text from "Process" to "Process Selected".  I kinda like that and I don't think it would be too much trouble to implement.

I can capture <ESC> in `ListViewFiles_KeyUp`, and mouse clicks in `ListViewFiles_MouseClick`.  That would let me set the button text accordingly.  I could change the button color, too I guess.

Wondering mostly if that covers all cases.  Thoughts?

**Comment by farfilli** [comment]
What if "process selected" is available only through the RMB menu?

Otherwise, a message box could appear before start processing by checking listviewfiles.selectesitems.count

**Comment by farfilli** [comment]
ButtonProcess text changes on selected items count, done in 4fe733dfd8106d44a90bd5113e458d60cf21d0cf

**Comment by rmcanany** [comment]
Nice.  Thank you!  Closing as complete.
