### ISSUE TITLE
Extend support to more file type

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#170]
This is an important change in the application and needs to be planned with several methods and functions to be updated.
The idea is to extend support for more file types, even if they are not directly related to Solid Edge.

I would implement PDFs first; let's start with some basic tasks like printing and watermarking.
The next batch would be to implement Word and Excel files and start with tasks like save as and print.
Another batch would be to manage step files, parasolids, and so on, and implement the conversion to Solid Edge files.

@rmcanany what do you think? Is it something you would consider or strictly Solid Edge files?

_Note: to be able to manage PDFs as I plan there is the need for an external DLL, I would choose from an open-source one; there are many so it will need some test to choose it. Something like:_
- https://github.com/empira/PDFsharp-1.5
- https://github.com/QuestPDF/QuestPDF

**Comment by rmcanany** [comment]
That's a cool idea.  We can talk more when I get back.

**Comment by farfilli** [comment]
I have created a discussion about this topic where we can start to plan changes to make it possible and then open specific issues for each one.
