### ISSUE TITLE
Save drawing as

### ISSUE THREAD

**Issue by FERNANDO-DALLAGNOLO** [rmcanany/SolidEdgeHousekeeper#173]
I would like to have the option to save drawing as in more than one extension in the same configuration.
For example, PDF and DWG

**Comment by farfilli** [comment]
You can do it by adding two save drawing as and configure them accordingly

**Comment by farfilli** [comment]
Something like this:
![image](https://github.com/user-attachments/assets/6e5cf8d5-7ea8-4217-8600-3130e4a2750a)

**Comment by rmcanany** [comment]
Closing as complete.  Thank you!
