### ISSUE TITLE
Will there be a Chinese version?

### ISSUE THREAD

**Issue by chjchen** [rmcanany/SolidEdgeHousekeeper#182]
A very good tool, will there be a Chinese version in the future?

**Comment by farfilli** [comment]
The tool is not written for localization, it would need a big effort to do it.
Let's see if it's ok for Robert to do such important improvements. I'll do my part of course.

**Comment by chjchen** [comment]
Thank you,I hope to be able to use it soon.

**Comment by farfilli** [comment]
In case you will have to contribute with the Chinese translation

**Comment by rmcanany** [comment]
Thank you for the suggestion!  

There are no plans for that right now, unfortunately.  However, if someone wanted to take it on, I'm sure a lot of users would welcome the improvement!

**Comment by farfilli** [comment]
This [link ](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-mat)contains the instructions on how to implement multi-lingual support.
Once the application is structured to support it, adding a language is an easy task.
However, the [first step](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest) to perform could be a big work, therefore we have to consider and plan it in case.
