### ISSUE TITLE
Property Filter

### ISSUE THREAD

**Issue by FERNANDO-DALLAGNOLO** [rmcanany/SolidEdgeHousekeeper#183]
Hi,

How can I configure the filter so that files that have the word OXICORTE in their name do not appear in the results?

![image](https://github.com/user-attachments/assets/d7b707eb-0f8c-4475-bc8d-c7f633b11fe5)

**Comment by farfilli** [comment]
You need to insert the wildcard "*" in front of "- OXIXORTE.dft"

**Comment by FERNANDO-DALLAGNOLO** [comment]
> You need to insert the wildcard "*" in front of "- OXIXORTE.dft"

In the wildcard I put *D2303011* to find only the manufactured files and not include standardized items such as screws, washers and pins. But in these results I find the 2D files that contain OXICORTE in their filename and I don't want these files to appear in the results.
The way you suggested works but it's not what I need because this way it only finds the files that contain OXICORTE in the name.
for example:
there are two files
D2303011001.dft
D2303011001 - OXICORTE.dft

I want to filter and find only the first one, in this case:
D2303011001.dft

**Comment by farfilli** [comment]
![image](https://github.com/user-attachments/assets/ab1cab6d-86d4-46e0-b6ad-60cf7d423c1a)

**Comment by FERNANDO-DALLAGNOLO** [comment]
it doesn't work, it still finds all the files
![image](https://github.com/user-attachments/assets/3c9bb617-553f-4149-89eb-ea7ca763e3f5)

**Comment by farfilli** [comment]
There must be a bug cause the "is not" always revert to "contains"; @rmcanany can you take a look at this situation?

**Comment by FERNANDO-DALLAGNOLO** [comment]
sorry, but it's not working
I thought it could be the space or the hyphen but it's not
I've done several tests, and it works as you indicated when I filter by the letter W for example, the app eliminates the results composed of D2303011W01
D2303011W02
![image](https://github.com/user-attachments/assets/98d50e60-6292-44e3-8999-abaad9d1a23f)
there are 440 results without using a filter
![image](https://github.com/user-attachments/assets/f676176d-5986-4c1c-a467-cdf8142f3642)
and 158 results with the filter on the letter W
![image](https://github.com/user-attachments/assets/7bebfc20-753a-4909-a3c9-95e9d3c1c2ec)

**Comment by rmcanany** [comment]
One other thing to check.  For Draft files there is an option to also check properties of the model files it contains.  It's on by default, but might be worth turning off for this case.  The option is on the **Configuration Tab -- General Page**.  Please try that and let me know how it goes.

![include_model_files](https://github.com/user-attachments/assets/ed0b2047-a5ca-4c0f-adff-8e6363a536b4)

**Comment by rmcanany** [comment]
Thinking more about it, you might also have to enable the option `include the draft file itself`.

**Comment by FERNANDO-DALLAGNOLO** [comment]
sorry, but it's not working

**Comment by FERNANDO-DALLAGNOLO** [comment]
I made some test files, in total there are 10 files
![image](https://github.com/user-attachments/assets/89abbb06-b1b6-4366-bc34-256b9d7c8291)
when applying the filter to eliminate from the results the files that contain the word TEST in the name and the result is this
![image](https://github.com/user-attachments/assets/b013474f-cf89-4188-b3fa-7d7ec7ff0c7b)
![image](https://github.com/user-attachments/assets/3f8e5a60-53ad-4178-81a3-15b47ddfe26f)
it did not delete the dft files
![image](https://github.com/user-attachments/assets/468e6ea2-5092-4427-80fc-979a385a8a30)

**Comment by rmcanany** [comment]
Sounds like a bug.  I'll dig into it this afternoon.  

In the meantime, try to uncheck `Property Filter -- Include Draft file model documents in search`.

**Comment by rmcanany** [comment]
Got it.  Thank you.

It seems to work with options set like this: `Exclude models`, `Include drafts`.  See images below.  

In the test case, the two drafts with TESTE in the name contain models without that text in their own names.  That's where the match is coming from.  

In the original case you presented, it was either that, and/or the fact `.dft` was part of the filter.  No model names end in `dft`, so you would get a match on that basis, too.

Anyway, my test results are below.  Please let me know if it doesn't work for you with those settings.  It's still possible there's a bug somewhere.

All files:
![no_filter](https://github.com/user-attachments/assets/b6fcc58e-2847-4e36-a63b-032adabe72f4)

Property filter:
![property_filter](https://github.com/user-attachments/assets/5857b538-96a9-4204-bb08-687856f5f955)

Property search options:
![exclude_models_include_draft](https://github.com/user-attachments/assets/276fb1f5-d839-45ad-abe5-13f69564300c)

Results:
![exclude_models_include_draft_results](https://github.com/user-attachments/assets/c1624552-3701-4595-8a20-2c1884405294)

**Comment by FERNANDO-DALLAGNOLO** [comment]
That way it worked, thanks
