### ISSUE TITLE
PMI and sketch no hiding

### ISSUE THREAD

**Issue by tempod** [rmcanany/SolidEdgeHousekeeper#38]
HI.
First of all congratulations and thanks for this fantastic program.
I have noticed some strange behavior. Even selecting the options to hide the buildings they are still shown.
I made a little video for you to see. It seems that they are correctly hidden but then on the saved file they are still visible
![Recording 2023-03-20 at 16 03 48](https://user-images.githubusercontent.com/71033514/226381511-a204dc13-3e2d-447a-9379-eb90586fb4a9.gif)

**Comment by rmcanany** [comment]
Thank you for the feedback.  You're right.  I've noticed that, too.  I'll add it to the list!

I don't use Sync.  When working interactively, do you know the proper steps to hide those elements?

**Comment by tempod** [comment]
I don't use synchronous mode either.
to hide everything right click on "Design Bodies" and then on "Show Only"
![mostra solo](https://user-images.githubusercontent.com/71033514/226400087-c5770fc8-37af-42f0-bb48-bc78e127e65f.gif)

**Comment by rmcanany** [comment]
OK, cool  I'll try that.

**Comment by rmcanany** [comment]
Hi @tempod ,

I just pushed a release that includes a fix for this issue.  If you have a chance, please test it out and let me know how it goes.  Thank you!

**Comment by tempod** [comment]
Hello.
I tried and the problem disappeared!
Works great!!
Congratulations again!
