### ISSUE TITLE
Do not alter the "Most Recently Used" files list

### ISSUE THREAD

**Issue by farfilli** [rmcanany/SolidEdgeHousekeeper#44]
I think it would be useful to not alter the most recently used (MRU) list of files in Solid Edge.

To do this just add **Application.SuspendMRU()** when starting\connecting to Solid Edge and adding **Application.ResumeMRU()** when closing (well, since you are closing the app this step in unnecessarily)

I have successfully used this method in one of my internal programs that creates on the fly different pipes length that I have no interest in appearing in the MRU Files list

EWventually add an option to activate or not the MRU files list update\suspend

**Comment by rmcanany** [comment]
Slick!  Done.  Option is on the Configuration Tab, Miscellaneous Group.
