### ISSUE TITLE
Update styles from template -- Do the update in-place instead of moving elements to a new file

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#7]
Suggested by @farfilli.  Would preserve creation date and solve several other issues.

**Comment by farfilli** [comment]
With the latest commit the UpdateDimensionStyles can become UpdateStyles, just uncomment lines from 630 to 700
Changes to the task name must be done where used

**Comment by rmcanany** [comment]
I see the changes on your GitHub page, but not on mine.  I've forgotten how to do the update.  Do you have to issue a pull request or something?

**Comment by rmcanany** [comment]
Never mind.  I found your pull request.  I'll play around with it.  Thank you!

**Comment by rmcanany** [comment]
This is working great!  Closing...
