### ISSUE TITLE
Build releases using GitHub Actions

### ISSUE THREAD

**Issue by HumbleDeer** [rmcanany/SolidEdgeHousekeeper#70]
Releases on GitHub can be built automatically with a CI script, using a feature called GitHub Actions

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

**Comment by rmcanany** [comment]
I will check it out.  Thank you!

**Comment by rmcanany** [comment]
Oh, ça c'est trop pour moi -- j'y comprends rien du tout!  Merci quand même.
