### ISSUE TITLE
External program to break part copy links

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#72]
https://community.sw.siemens.com/s/question/0D5KZ0000064tOQ0AY/is-there-a-way-to-mass-unlink-part-copies?t=1705694826267

**Comment by ChrisNeCle** [comment]
I have a quick and dirty script written up that I use to do this already. All of my current SE automation tools are C# CLI apps and I'm going through them to see what I can/should port over to Housekeeper tasks. I'll look into building this from my currently existing code.

**Comment by rmcanany** [comment]
Great!  I'm sure you already know this, but I've had decent luck using the Telerik converter.  https://converter.telerik.com/
