### ISSUE TITLE
Copy and Set Styles

### ISSUE THREAD

**Issue by tempod** [rmcanany/SolidEdgeHousekeeper#75]
HI. I have two requests that are related to each other.

When I use "update face and view styles from template" only the currently used style is copied. Would it be possible to add an option to copy all the styles present in the template?
The second request concerns the possibility of setting a style when saving images of the pieces.
For example, when modeling the parts I use a gray background while when saving the images I set a style with a white background.
If it were possible to copy all the styles and set a style when saving it would be a nice progress in my opinion.

Thanks anyway for the excellent work.

**Comment by rmcanany** [comment]
Those are great ideas.  They're on the list!  Thank you!

**Comment by rmcanany** [comment]
@farfilli couldn't I just adopt your technique from UpdateDrawingStylesFromTemplate to tackle this one?

**Comment by farfilli** [comment]
I think there is an API to easily manage the styles, I will have a look and return it

**Comment by rmcanany** [comment]
@tempod I appreciate your great suggestions!  It should be working now.  If you can't compile from source, let me know and I'll zip up a pre-release for you.  

@farfilli I copied your technique from UpdateDrawingStylesFromTemplate.  Much easier and better.  I didn't even have to _touch_ your CopyProperties code.  Nice!

**Comment by rmcanany** [comment]
Closing as complete.

**Comment by tempod** [comment]
wow! thank you so much. unfortunately i dont know how to compile from source...

**Comment by rmcanany** [comment]
OK, no problem.  I've got one last issue to address, then am going to release it for beta test.  It should be ready in a week or two.  I'll let you know when it has posted and you can try it out then.

**Comment by rmcanany** [comment]
@tempod 

I published the latest version of Housekeeper this morning.  Here are a couple of links to get you started:

[Release Notes](https://github.com/rmcanany/SolidEdgeHousekeeper/blob/master/release_notes.md)
[Installation Instructions](https://github.com/rmcanany/SolidEdgeHousekeeper#installation)
[Release Page](https://github.com/rmcanany/SolidEdgeHousekeeper/releases)

If you get a chance to try it out, I would welcome any feedback you may have.

Robert
