### ISSUE TITLE
Basic documentation for adding a new task under new heirarchy

### ISSUE THREAD

**Issue by ChrisClems** [rmcanany/SolidEdgeHousekeeper#85]
Can we get a brief writeup of how to add a new task under the new structure? I've attempted to add a new task. I created a new task file based on another task and added it to PreferenceUtilities.vb. It shows up in the Edit task list dialog. I cannot get it to show up in the Tasks tab. I have a couple of tasks I would like to add, but I'd like to get them in cleanly using the new and improved structure. I looked through the rest of the project and I don't see any other logic building the tasks list, though I'm not usually a VB.Net user so I may be overlooking something.

You can see what I've done in my RegenFlatModel branch if it helps: https://github.com/ChrisNeCle/SolidEdgeHousekeeper/tree/RegenFlatModel

**Comment by rmcanany** [comment]
Adding it to BuildTaskListFromScratch() like you did is what I would have suggested.  As you know, I started the task list updates but got interrupted and haven't finished.  I'm dying to do so, but it will be a while, unfortunately.  

In the mean time, when I get a chance I'll dig around and see if I can at least get you going.

**Comment by rmcanany** [comment]
What happens if you delete task_list.json in the Preferences directory?

**Comment by ChrisNeCle** [comment]
That seemed to do the trick. It's working now. I'll put together another PR once I can get through some more testing. I can also start an issue for the task list not updating between updates if that would be helpful.

**Comment by rmcanany** [comment]
Sounds good.  Looking forward to seeing your handywork!

Yes, please add an issue about the task list not updating.  It shouldn't be hard to fix, but might be hard (for me) to remember.

**Comment by rmcanany** [comment]
No, that's where I left off.  It lets you make changes on the form, but does not yet update the real task list.

**Comment by rmcanany** [comment]
Getting back to the original request, I added a quick note in Form1.vb, just below the Property Declarations.  It's more of a placeholder for now, but if you think of anything I should add, please don't hesitate to let me know.

**Comment by rmcanany** [comment]
Closing as complete.
