### ISSUE TITLE
Task list not updating between builds

### ISSUE THREAD

**Issue by ChrisClems** [rmcanany/SolidEdgeHousekeeper#86]
Adding a new task and updating the task list in BuildTaskListFromScratch() will not update the task list if task_list.json exists in the target Preferences directory.

**Comment by rmcanany** [comment]
I think this is now fixed with the `Edit Task List` functionality.  The source panel gets its Task List using `BuildTaskListFromScratch`, so everything should be available.  If you concur, I'll close this a complete.

**Comment by farfilli** [comment]
@rmcanany for some reason the border drawn with UCTaskControl_Paint doesn't appear, do you know what could have broken it? In my opinion, this border is needed to distinguish better between tasks

**Comment by rmcanany** [comment]
I appreciate the feedback.  Should be fixed now.

I'm pretty sure there's a gremlin in there somewhere.  Yesterday I had to change all the Form fonts from Microsoft Sans Serif back to Segoe.

**Comment by farfilli** [comment]
@rmcanany If you have a look at the UCTaskControl_Paint event I have tweaked it to paint only the Top border.
With your modification, all the TLP borders are drawn which is not what I intended.

**Comment by farfilli** [comment]
@rmcanany I fixed it with pull request #110

**Comment by rmcanany** [comment]
Ok, thanks for that.  It's perfect!  Closing as complete.
